server.port: 8888

spring.cloud.config.server.git:
  uri: https://github.com/sarathkam/config-git-repo.git
  skipSslValidation: true

#spring.profiles.active: native
#spring.cloud.config.server.native.searchLocations: file:///C:/workspace/config-git-repo

management.endpoints.web.base-path: /admin
